SELECT CAR_ID, 
  CASE 
    WHEN SUM(IF('2022-10-16' BETWEEN START_DATE AND END_DATE, 1, 0))=0 then "대여 가능" 
    else "대여중" 
  end AS AVAILBILITY 
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
GROUP BY CAR_ID 
ORDER BY CAR_ID DESC;